#!/bin/sh
### BEGIN INIT INFO
# Provides:       rpphone.sh
# Required-Start:  
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start or stop rpphone.sh
### END INIT INFO

case $1 in
	start)
		rpphone.sh &
		;;
	stop)
		killall rpphone.sh
		;;
	*)
		echo "Usage: $0 (start|stop)"
		;;
esac
